// Generated by scripts/generate-gallery.ps1 - do not edit by hand
window.BULAMU_DATA = window.BULAMU_DATA || {};
window.BULAMU_DATA.GALLERY = [
    {
        "src":  "img/buildings/clinic.jpg",
        "srcLarge":  "img/buildings/clinic.jpg",
        "filename":  "clinic.jpg",
        "cap":  "clinic",
        "category":  "buildings"
    },
    {
        "src":  "img/buildings/dispensary.jpg",
        "srcLarge":  "img/buildings/dispensary.jpg",
        "filename":  "dispensary.jpg",
        "cap":  "dispensary",
        "category":  "buildings"
    },
    {
        "src":  "img/buildings/pharmacy.jpg",
        "srcLarge":  "img/buildings/pharmacy.jpg",
        "filename":  "pharmacy.jpg",
        "cap":  "pharmacy",
        "category":  "buildings"
    },
    {
        "src":  "img/cover image/home.jpg",
        "srcLarge":  "img/cover image/home.jpg",
        "filename":  "home.jpg",
        "cap":  "home",
        "category":  "cover image"
    },
    {
        "src":  "img/insurance cover/AAR.jpg",
        "srcLarge":  "img/insurance cover/AAR.jpg",
        "filename":  "AAR.jpg",
        "cap":  "AAR",
        "category":  "insurance cover"
    },
    {
        "src":  "img/insurance cover/CASE HOSPITAL.jpg",
        "srcLarge":  "img/insurance cover/CASE HOSPITAL.jpg",
        "filename":  "CASE HOSPITAL.jpg",
        "cap":  "CASE HOSPITAL",
        "category":  "insurance cover"
    },
    {
        "src":  "img/insurance cover/IAA.jpg",
        "srcLarge":  "img/insurance cover/IAA.jpg",
        "filename":  "IAA.jpg",
        "cap":  "IAA",
        "category":  "insurance cover"
    },
    {
        "src":  "img/insurance cover/jubilee.jpg",
        "srcLarge":  "img/insurance cover/jubilee.jpg",
        "filename":  "jubilee.jpg",
        "cap":  "jubilee",
        "category":  "insurance cover"
    },
    {
        "src":  "img/insurance cover/liberty.jpg",
        "srcLarge":  "img/insurance cover/liberty.jpg",
        "filename":  "liberty.jpg",
        "cap":  "liberty",
        "category":  "insurance cover"
    },
    {
        "src":  "img/insurance cover/sanlam.jpg",
        "srcLarge":  "img/insurance cover/sanlam.jpg",
        "filename":  "sanlam.jpg",
        "cap":  "sanlam",
        "category":  "insurance cover"
    },
    {
        "src":  "img/insurance cover/UAP.jpg",
        "srcLarge":  "img/insurance cover/UAP.jpg",
        "filename":  "UAP.jpg",
        "cap":  "UAP",
        "category":  "insurance cover"
    },
    {
        "src":  "img/insurance cover/XCEE.jpg",
        "srcLarge":  "img/insurance cover/XCEE.jpg",
        "filename":  "XCEE.jpg",
        "cap":  "XCEE",
        "category":  "insurance cover"
    },
    {
        "src":  "img/news/OUR SENIOR DOCTOR SENSITIZED THE COMMUNITY KAWANDA CHUCH OF UGANDA. 2016.jpg",
        "srcLarge":  "img/news/OUR SENIOR DOCTOR SENSITIZED THE COMMUNITY KAWANDA CHUCH OF UGANDA. 2016.jpg",
        "filename":  "OUR SENIOR DOCTOR SENSITIZED THE COMMUNITY KAWANDA CHUCH OF UGANDA. 2016.jpg",
        "cap":  "OUR SENIOR DOCTOR SENSITIZED THE COMMUNITY KAWANDA CHUCH OF UGANDA. 2016",
        "category":  "news"
    },
    {
        "src":  "img/news/out reach with USAID 2017.jpg",
        "srcLarge":  "img/news/out reach with USAID 2017.jpg",
        "filename":  "out reach with USAID 2017.jpg",
        "cap":  "out reach with USAID 2017",
        "category":  "news"
    },
    {
        "src":  "img/news/some of the donated equipement from USAID out reach.jpg",
        "srcLarge":  "img/news/some of the donated equipement from USAID out reach.jpg",
        "filename":  "some of the donated equipement from USAID out reach.jpg",
        "cap":  "some of the donated equipement from USAID out reach",
        "category":  "news"
    },
    {
        "src":  "img/news/THE FRONT VIEW OF KAWANDA PRIMARY SCHOOL. 2016.jpg",
        "srcLarge":  "img/news/THE FRONT VIEW OF KAWANDA PRIMARY SCHOOL. 2016.jpg",
        "filename":  "THE FRONT VIEW OF KAWANDA PRIMARY SCHOOL. 2016.jpg",
        "cap":  "THE FRONT VIEW OF KAWANDA PRIMARY SCHOOL. 2016",
        "category":  "news"
    },
    {
        "src":  "img/news/THROUGH CHILD EDUCATION, WE ALL BELIEVE SUCCESS CAN BE ACHIEVED IN LIFE..jpg",
        "srcLarge":  "img/news/THROUGH CHILD EDUCATION, WE ALL BELIEVE SUCCESS CAN BE ACHIEVED IN LIFE..jpg",
        "filename":  "THROUGH CHILD EDUCATION, WE ALL BELIEVE SUCCESS CAN BE ACHIEVED IN LIFE..jpg",
        "cap":  "THROUGH CHILD EDUCATION, WE ALL BELIEVE SUCCESS CAN BE ACHIEVED IN LIFE.",
        "category":  "news"
    },
    {
        "src":  "img/news/WE DO SUPPORT RULAR EDUCATION AT KAWANDA PRIMARY SCH.jpg",
        "srcLarge":  "img/news/WE DO SUPPORT RULAR EDUCATION AT KAWANDA PRIMARY SCH.jpg",
        "filename":  "WE DO SUPPORT RULAR EDUCATION AT KAWANDA PRIMARY SCH.jpg",
        "cap":  "WE DO SUPPORT RULAR EDUCATION AT KAWANDA PRIMARY SCH",
        "category":  "news"
    },
    {
        "src":  "img/services/announcement.jpg",
        "srcLarge":  "img/services/announcement.jpg",
        "filename":  "announcement.jpg",
        "cap":  "announcement",
        "category":  "services"
    },
    {
        "src":  "img/services/bulama shift schedule for staff.jpg",
        "srcLarge":  "img/services/bulama shift schedule for staff.jpg",
        "filename":  "bulama shift schedule for staff.jpg",
        "cap":  "bulama shift schedule for staff",
        "category":  "services"
    },
    {
        "src":  "img/services/clinic.jpg",
        "srcLarge":  "img/services/clinic.jpg",
        "filename":  "clinic.jpg",
        "cap":  "clinic",
        "category":  "services"
    },
    {
        "src":  "img/services/immunization services.jpg",
        "srcLarge":  "img/services/immunization services.jpg",
        "filename":  "immunization services.jpg",
        "cap":  "immunization services",
        "category":  "services"
    },
    {
        "src":  "img/services/nurse injecting patient.jpg",
        "srcLarge":  "img/services/nurse injecting patient.jpg",
        "filename":  "nurse injecting patient.jpg",
        "cap":  "nurse injecting patient",
        "category":  "services"
    },
    {
        "src":  "img/services/nusrse injecting male patient.jpg",
        "srcLarge":  "img/services/nusrse injecting male patient.jpg",
        "filename":  "nusrse injecting male patient.jpg",
        "cap":  "nusrse injecting male patient",
        "category":  "services"
    },
    {
        "src":  "img/services/service doc.jpg",
        "srcLarge":  "img/services/service doc.jpg",
        "filename":  "service doc.jpg",
        "cap":  "service doc",
        "category":  "services"
    },
    {
        "src":  "img/THE EQUIPMENTS AND MACHINES/-ROLLER MIXER.jpg",
        "srcLarge":  "img/THE EQUIPMENTS AND MACHINES/-ROLLER MIXER.jpg",
        "filename":  "-ROLLER MIXER.jpg",
        "cap":  " ROLLER MIXER",
        "category":  "THE EQUIPMENTS AND MACHINES"
    },
    {
        "src":  "img/THE EQUIPMENTS AND MACHINES/2 Ambulances.jpg",
        "srcLarge":  "img/THE EQUIPMENTS AND MACHINES/2 Ambulances.jpg",
        "filename":  "2 Ambulances.jpg",
        "cap":  "2 Ambulances",
        "category":  "THE EQUIPMENTS AND MACHINES"
    },
    {
        "src":  "img/THE EQUIPMENTS AND MACHINES/AN ADVANCED THEATER.jpg",
        "srcLarge":  "img/THE EQUIPMENTS AND MACHINES/AN ADVANCED THEATER.jpg",
        "filename":  "AN ADVANCED THEATER.jpg",
        "cap":  "AN ADVANCED THEATER",
        "category":  "THE EQUIPMENTS AND MACHINES"
    },
    {
        "src":  "img/THE EQUIPMENTS AND MACHINES/CASHIERS DESK..jpg",
        "srcLarge":  "img/THE EQUIPMENTS AND MACHINES/CASHIERS DESK..jpg",
        "filename":  "CASHIERS DESK..jpg",
        "cap":  "CASHIERS DESK.",
        "category":  "THE EQUIPMENTS AND MACHINES"
    },
    {
        "src":  "img/THE EQUIPMENTS AND MACHINES/COME AND FEEL THE CONFART WITH OUR DENTAL..jpg",
        "srcLarge":  "img/THE EQUIPMENTS AND MACHINES/COME AND FEEL THE CONFART WITH OUR DENTAL..jpg",
        "filename":  "COME AND FEEL THE CONFART WITH OUR DENTAL..jpg",
        "cap":  "COME AND FEEL THE CONFART WITH OUR DENTAL.",
        "category":  "THE EQUIPMENTS AND MACHINES"
    },
    {
        "src":  "img/THE EQUIPMENTS AND MACHINES/ELECTROCARDIOGRAPH MACHINE (ECG).jpg",
        "srcLarge":  "img/THE EQUIPMENTS AND MACHINES/ELECTROCARDIOGRAPH MACHINE (ECG).jpg",
        "filename":  "ELECTROCARDIOGRAPH MACHINE (ECG).jpg",
        "cap":  "ELECTROCARDIOGRAPH MACHINE (ECG)",
        "category":  "THE EQUIPMENTS AND MACHINES"
    },
    {
        "src":  "img/THE EQUIPMENTS AND MACHINES/FULL AUTOMATED HAEMOTOLOGY ANALYSER..jpg",
        "srcLarge":  "img/THE EQUIPMENTS AND MACHINES/FULL AUTOMATED HAEMOTOLOGY ANALYSER..jpg",
        "filename":  "FULL AUTOMATED HAEMOTOLOGY ANALYSER..jpg",
        "cap":  "FULL AUTOMATED HAEMOTOLOGY ANALYSER.",
        "category":  "THE EQUIPMENTS AND MACHINES"
    },
    {
        "src":  "img/THE EQUIPMENTS AND MACHINES/FULL EQUIPED AND FURNISHED DENTAL WORKING CLINIC..jpg",
        "srcLarge":  "img/THE EQUIPMENTS AND MACHINES/FULL EQUIPED AND FURNISHED DENTAL WORKING CLINIC..jpg",
        "filename":  "FULL EQUIPED AND FURNISHED DENTAL WORKING CLINIC..jpg",
        "cap":  "FULL EQUIPED AND FURNISHED DENTAL WORKING CLINIC.",
        "category":  "THE EQUIPMENTS AND MACHINES"
    },
    {
        "src":  "img/THE EQUIPMENTS AND MACHINES/LAB TECHNICIANS..jpg",
        "srcLarge":  "img/THE EQUIPMENTS AND MACHINES/LAB TECHNICIANS..jpg",
        "filename":  "LAB TECHNICIANS..jpg",
        "cap":  "LAB TECHNICIANS.",
        "category":  "THE EQUIPMENTS AND MACHINES"
    },
    {
        "src":  "img/THE EQUIPMENTS AND MACHINES/microscope.jpg",
        "srcLarge":  "img/THE EQUIPMENTS AND MACHINES/microscope.jpg",
        "filename":  "microscope.jpg",
        "cap":  "microscope",
        "category":  "THE EQUIPMENTS AND MACHINES"
    },
    {
        "src":  "img/THE EQUIPMENTS AND MACHINES/MOVING CLINIC.jpg",
        "srcLarge":  "img/THE EQUIPMENTS AND MACHINES/MOVING CLINIC.jpg",
        "filename":  "MOVING CLINIC.jpg",
        "cap":  "MOVING CLINIC",
        "category":  "THE EQUIPMENTS AND MACHINES"
    },
    {
        "src":  "img/THE EQUIPMENTS AND MACHINES/OXYGEN,NEBULIZER,PATIENT MONITOR,WHEEL CHAIR, FIRE EXTINGUISHER AND FULL TO CAPACITY WITH ALL KINDS OF MEDICENE.jpg",
        "srcLarge":  "img/THE EQUIPMENTS AND MACHINES/OXYGEN,NEBULIZER,PATIENT MONITOR,WHEEL CHAIR, FIRE EXTINGUISHER AND FULL TO CAPACITY WITH ALL KINDS OF MEDICENE.jpg",
        "filename":  "OXYGEN,NEBULIZER,PATIENT MONITOR,WHEEL CHAIR, FIRE EXTINGUISHER AND FULL TO CAPACITY WITH ALL KINDS OF MEDICENE.jpg",
        "cap":  "OXYGEN,NEBULIZER,PATIENT MONITOR,WHEEL CHAIR, FIRE EXTINGUISHER AND FULL TO CAPACITY WITH ALL KINDS OF MEDICENE",
        "category":  "THE EQUIPMENTS AND MACHINES"
    },
    {
        "src":  "img/THE EQUIPMENTS AND MACHINES/PATIENTS MONITOR( ECG,Automated temperature,BP monitor).jpg",
        "srcLarge":  "img/THE EQUIPMENTS AND MACHINES/PATIENTS MONITOR( ECG,Automated temperature,BP monitor).jpg",
        "filename":  "PATIENTS MONITOR( ECG,Automated temperature,BP monitor).jpg",
        "cap":  "PATIENTS MONITOR( ECG,Automated temperature,BP monitor)",
        "category":  "THE EQUIPMENTS AND MACHINES"
    },
    {
        "src":  "img/THE EQUIPMENTS AND MACHINES/RECEPTION AREA 2.jpg",
        "srcLarge":  "img/THE EQUIPMENTS AND MACHINES/RECEPTION AREA 2.jpg",
        "filename":  "RECEPTION AREA 2.jpg",
        "cap":  "RECEPTION AREA 2",
        "category":  "THE EQUIPMENTS AND MACHINES"
    },
    {
        "src":  "img/THE EQUIPMENTS AND MACHINES/RECEPTION AREA..jpg",
        "srcLarge":  "img/THE EQUIPMENTS AND MACHINES/RECEPTION AREA..jpg",
        "filename":  "RECEPTION AREA..jpg",
        "cap":  "RECEPTION AREA.",
        "category":  "THE EQUIPMENTS AND MACHINES"
    },
    {
        "src":  "img/THE EQUIPMENTS AND MACHINES/reception.jpg",
        "srcLarge":  "img/THE EQUIPMENTS AND MACHINES/reception.jpg",
        "filename":  "reception.jpg",
        "cap":  "reception",
        "category":  "THE EQUIPMENTS AND MACHINES"
    },
    {
        "src":  "img/THE EQUIPMENTS AND MACHINES/SEMI-AUTOETED CHEISTRY ANALYSER.jpg",
        "srcLarge":  "img/THE EQUIPMENTS AND MACHINES/SEMI-AUTOETED CHEISTRY ANALYSER.jpg",
        "filename":  "SEMI-AUTOETED CHEISTRY ANALYSER.jpg",
        "cap":  "SEMI AUTOETED CHEISTRY ANALYSER",
        "category":  "THE EQUIPMENTS AND MACHINES"
    },
    {
        "src":  "img/THE EQUIPMENTS AND MACHINES/SOME OF THE LABORATORY EQUIPMENTS.jpg",
        "srcLarge":  "img/THE EQUIPMENTS AND MACHINES/SOME OF THE LABORATORY EQUIPMENTS.jpg",
        "filename":  "SOME OF THE LABORATORY EQUIPMENTS.jpg",
        "cap":  "SOME OF THE LABORATORY EQUIPMENTS",
        "category":  "THE EQUIPMENTS AND MACHINES"
    },
    {
        "src":  "img/THE EQUIPMENTS AND MACHINES/THANKS TO IHK (Kampala International Hospital) FOR TRUSTING US WITH YOUR PATIENTS LIFE..jpg",
        "srcLarge":  "img/THE EQUIPMENTS AND MACHINES/THANKS TO IHK (Kampala International Hospital) FOR TRUSTING US WITH YOUR PATIENTS LIFE..jpg",
        "filename":  "THANKS TO IHK (Kampala International Hospital) FOR TRUSTING US WITH YOUR PATIENTS LIFE..jpg",
        "cap":  "THANKS TO IHK (Kampala International Hospital) FOR TRUSTING US WITH YOUR PATIENTS LIFE.",
        "category":  "THE EQUIPMENTS AND MACHINES"
    },
    {
        "src":  "img/THE EQUIPMENTS AND MACHINES/THEATER BED , OXYGEN CONCETRATOR AND THEATER TOUCH..jpg",
        "srcLarge":  "img/THE EQUIPMENTS AND MACHINES/THEATER BED , OXYGEN CONCETRATOR AND THEATER TOUCH..jpg",
        "filename":  "THEATER BED , OXYGEN CONCETRATOR AND THEATER TOUCH..jpg",
        "cap":  "THEATER BED , OXYGEN CONCETRATOR AND THEATER TOUCH.",
        "category":  "THE EQUIPMENTS AND MACHINES"
    },
    {
        "src":  "img/THE EQUIPMENTS AND MACHINES/THEATER EQUIPMENTS STAND.jpg",
        "srcLarge":  "img/THE EQUIPMENTS AND MACHINES/THEATER EQUIPMENTS STAND.jpg",
        "filename":  "THEATER EQUIPMENTS STAND.jpg",
        "cap":  "THEATER EQUIPMENTS STAND",
        "category":  "THE EQUIPMENTS AND MACHINES"
    },
    {
        "src":  "img/THE EQUIPMENTS AND MACHINES/ULTRA SOUND AND ELECTROCARDIOGRAPH MACHINES..jpg",
        "srcLarge":  "img/THE EQUIPMENTS AND MACHINES/ULTRA SOUND AND ELECTROCARDIOGRAPH MACHINES..jpg",
        "filename":  "ULTRA SOUND AND ELECTROCARDIOGRAPH MACHINES..jpg",
        "cap":  "ULTRA SOUND AND ELECTROCARDIOGRAPH MACHINES.",
        "category":  "THE EQUIPMENTS AND MACHINES"
    },
    {
        "src":  "img/THE EQUIPMENTS AND MACHINES/URYSIS MACHINE.jpg",
        "srcLarge":  "img/THE EQUIPMENTS AND MACHINES/URYSIS MACHINE.jpg",
        "filename":  "URYSIS MACHINE.jpg",
        "cap":  "URYSIS MACHINE",
        "category":  "THE EQUIPMENTS AND MACHINES"
    },
    {
        "src":  "img/THE EQUIPMENTS AND MACHINES/WASHING MACHINE.jpg",
        "srcLarge":  "img/THE EQUIPMENTS AND MACHINES/WASHING MACHINE.jpg",
        "filename":  "WASHING MACHINE.jpg",
        "cap":  "WASHING MACHINE",
        "category":  "THE EQUIPMENTS AND MACHINES"
    },
    {
        "src":  "img/THE EQUIPMENTS AND MACHINES/WATER BATH AND LAB-COMPUTER.jpg",
        "srcLarge":  "img/THE EQUIPMENTS AND MACHINES/WATER BATH AND LAB-COMPUTER.jpg",
        "filename":  "WATER BATH AND LAB-COMPUTER.jpg",
        "cap":  "WATER BATH AND LAB COMPUTER",
        "category":  "THE EQUIPMENTS AND MACHINES"
    },
    {
        "src":  "img/THE EQUIPMENTS AND MACHINES/We work hand in hand with IHK (International Hospital kampala).jpg",
        "srcLarge":  "img/THE EQUIPMENTS AND MACHINES/We work hand in hand with IHK (International Hospital kampala).jpg",
        "filename":  "We work hand in hand with IHK (International Hospital kampala).jpg",
        "cap":  "We work hand in hand with IHK (International Hospital kampala)",
        "category":  "THE EQUIPMENTS AND MACHINES"
    },
    {
        "src":  "img/THE EQUIPMENTS AND MACHINES/WHEN LIFE IS HANGING BY A THREAD CALL OUR INTENSIVE CARE CHEAP AMBULANCE 🚑.jpg",
        "srcLarge":  "img/THE EQUIPMENTS AND MACHINES/WHEN LIFE IS HANGING BY A THREAD CALL OUR INTENSIVE CARE CHEAP AMBULANCE 🚑.jpg",
        "filename":  "WHEN LIFE IS HANGING BY A THREAD CALL OUR INTENSIVE CARE CHEAP AMBULANCE 🚑.jpg",
        "cap":  "WHEN LIFE IS HANGING BY A THREAD CALL OUR INTENSIVE CARE CHEAP AMBULANCE 🚑",
        "category":  "THE EQUIPMENTS AND MACHINES"
    }
];

