Param()

$ErrorActionPreference = 'Stop'

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$projectRoot = Resolve-Path (Join-Path $scriptDir '..')
$imgDir = Join-Path $projectRoot 'img'
$outFile = Join-Path $projectRoot 'js\gallery-data.js'

$exts = @('.jpg','.jpeg','.png','.webp','.gif')

if (-Not (Test-Path $imgDir)) {
  Write-Error "img directory not found: $imgDir"
  exit 1
}

$files = Get-ChildItem -Path $imgDir -Recurse -File | Where-Object { $exts -contains $_.Extension.ToLower() } | ForEach-Object {
  $full = $_.FullName
  $rel = $full.Substring($projectRoot.Path.Length + 1) -replace '\\','/'
  $parts = $rel -split '/'
  $category = if ($parts.Length -gt 1) { $parts[1] } else { 'root' }
  [PSCustomObject]@{
    src = $rel
    srcLarge = $rel
    filename = $_.Name
    cap = ([regex]::Replace($_.BaseName, '[-_]+', ' '))
    category = $category
  }
}

$json = $files | ConvertTo-Json -Depth 6

$content = "// Generated by scripts/generate-gallery.ps1 - do not edit by hand`nwindow.BULAMU_DATA = window.BULAMU_DATA || {};`nwindow.BULAMU_DATA.GALLERY = $json;`n"

Set-Content -Path $outFile -Value $content -Encoding UTF8

Write-Output "Wrote $outFile with $($files.Count) images"
