const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const imgDir = path.join(root, 'img');
const outFile = path.join(root, 'js', 'gallery-data.js');

const exts = ['.jpg', '.jpeg', '.png', '.webp', '.gif'];

function walk(dir) {
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  let files = [];
  for (const e of entries) {
    const full = path.join(dir, e.name);
    if (e.isDirectory()) files = files.concat(walk(full));
    else if (e.isFile() && exts.includes(path.extname(e.name).toLowerCase())) files.push(full);
  }
  return files;
}

function rel(p) {
  return p.split(path.sep).join('/').replace(root.replace(/\\/g, '/'), '').replace(/^\//, '');
}

function slugToTitle(s) {
  return s.replace(/[-_]+/g, ' ').replace(/\.[^.]+$/, '').replace(/\b\w/g, c => c.toUpperCase());
}

if (!fs.existsSync(imgDir)) {
  console.error('img directory not found at', imgDir);
  process.exit(1);
}

const files = walk(imgDir).map(f => {
  const parts = f.split(path.sep);
  // category: first folder under img (if any)
  const imgIndex = parts.findIndex(p => p === 'img');
  const after = parts.slice(imgIndex + 1);
  const category = after.length > 1 ? after[0] : (after.length === 1 ? 'root' : 'root');
  const filename = parts[parts.length - 1];
  return {
    src: rel(f),
    srcLarge: rel(f),
    filename,
    cap: slugToTitle(filename),
    category
  };
});

const out = '// Generated by scripts/generate-gallery.js - do not edit by hand\nwindow.BULAMU_DATA = window.BULAMU_DATA || {};\nwindow.BULAMU_DATA.GALLERY = ' + JSON.stringify(files, null, 2) + ';\n';
fs.writeFileSync(outFile, out, 'utf8');
console.log('Wrote', outFile, 'with', files.length, 'images');
